{% set name = "colcon-zsh" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/colcon-zsh-{{ version }}.tar.gz
  sha256: efff75c43ddab2649853529e41cee36e0f83b6d4c864c0736353d0dece78334a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - colcon-core >=0.4.0
    - python >={{ python_min }}

test:
  imports:
    - colcon_zsh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to provide Z shell scripts.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-rivero
    - Tobias-Fischer
